# If set to true, matches only one taboo per message
match-once: true
# If set to false, Taboo won't try to load action classes from "actions" directory
enable-actions-classloader: true
# If set to true, enabled debug log messages
debug: false

actions:
    kick:
        class: Kick
        message: "You have been kicked for using bad words"
    msg1:
        class: Message
        message: "Don't say this again"
    msg2:
        class: Message
        message: "Shut up!"

taboos:
    damn:
        patterns:
            - "damn"
        replacement: "darn"
        include-permission: taboo.include.damn
        actions:
            - msg1
    admin-whine:
        patterns:
            - /\Aadmin\Z/
        mute: true
        actions:
            - kick