name: ${project.name}
version: ${project.version}-b${buildNumber}
description: ${project.description}
website: ${project.url}
author: ${project.organization.name}

main: ${project.groupId}.${project.artifactId}.layer.bukkit.${project.artifactName}
load: startup
