name: ${project.name}
version: ${project.version}-b${buildNumber}
description: ${project.description}
website: ${project.url}
author: ${project.organization.name}

main: ${project.groupId}.${project.artifactId}.layer.bukkit.${project.name}Plugin
load: startup

commands:
    ${project.artifactId}:
        description: Info about Taboo and config reload.
        permission: ${project.artifactId}.reload
        usage: |
            ${project.name} ${project.version} by ${project.organization.name} (${project.url})
            Usage:
            /<command> reload - reload config.yml
